Feature: 034 - CODED CARTOGRAPHIC MATHEMATICAL DATA 
  Background: 
    Given a marc field "=033  21$3Horse$a197809102000-0400$a197809142000-0400$b6714$cR7$b6714$cV4$pMinneapolis City Hall-Hennepin County Courthouse (Minneapolis, Minn.)$2lcsh"
    When converted by a field converter io.lold.marc2bf2.converters.Field033Converter

  Scenario: ind1 determines the type of dates represented by $a in the capture/Capture/date property of the Work
    When I search with patterns:
      | ?x a bf:Work                         |
      | ?x bf:capture ?y                     |
      | ?y a bf:Capture                      |
      | ?y bf:date ?z                        |
      #| ?y bf:date "1978-09-10T20:00:00-04:00/1978-09-14T20:00:00-04:00"^^<http://id.loc.gov/datatypes/edtf> |
    Then I should find 1 match

  Scenario: ind2 generates a note property in the Capture
    When I search with patterns:
      | ?x a bf:Work                         |
      | ?x bf:capture ?y                     |
      | ?y a bf:Capture                      |
      | ?y bf:note ?z                        |
      | ?z a bf:Note                         |
      | ?z rdfs:label "broadcast"            |
    Then I should find 1 match

  Scenario: $b and $c create a place property of the Capture with a source property
    When I search with patterns:
      | ?x a bf:Work                         |
      | ?x bf:capture ?y                     |
      | ?y a bf:Capture                      |
      | ?y bf:place ?z                       |
      | ?z a bf:Place                        |
      | ?z rdf:value "6714 V4"               |
      | ?z bf:source ?s                      |
      | ?s a bf:Source                       |
      | ?s rdfs:label "lcc-g"                |
    Then I should find 1 match

  Scenario: $p creates a place property of the Capture
    When I search with patterns:
      | ?x a bf:Work                         |
      | ?x bf:capture ?y                     |
      | ?y a bf:Capture                      |
      | ?y bf:place ?z                       |
      | ?z a bf:Place                        |
      | ?z rdfs:label "Minneapolis City Hall-Hennepin County Courthouse (Minneapolis, Minn.)" |
    Then I should find 1 match

  Scenario: $2 creates a source property of the place (generated by $p)
    When I search with patterns:
      | ?x a bf:Work                         |
      | ?x bf:capture ?y                     |
      | ?y a bf:Capture                      |
      | ?y bf:place ?z                       |
      | ?z a bf:Place                        |
      | ?z bf:source ?s                      |
      | ?s a bf:Source                       |
      | ?s rdfs:label "lcsh"                 |
    Then I should find 1 match

  Scenario: $3 creates a bflc:appliesTo property of the Capture
    When I search with patterns:
      | ?x a bf:Work                         |
      | ?x bf:capture ?y                     |
      | ?y a bf:Capture                      |
      | ?y bflc:appliesTo  ?z                |
      | ?z a bflc:AppliesTo                  |
      | ?z rdfs:label "Horse"                |
    Then I should find 1 match
