package io.lold.marc2bf2.vocabulary;

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

import java.util.Collection;

public class BIB_FRAME {
    private static final Model m = ModelFactory.createDefaultModel();
    public static final String NAMESPACE = "http://id.loc.gov/ontologies/bibframe/";
    public static final String PREFIX = "bf";

    public static String getURI() {
        return NAMESPACE;
    }

    // ---- classes ----
    public static final Resource Work;
    public static final Resource Instance;
    public static final Resource Item;
    public static final Resource Text;
    public static final Resource Cartography;
    public static final Resource Audio;
    public static final Resource NotatedMusic;
    public static final Resource NotatedMovement;
    public static final Resource Dataset;
    public static final Resource StillImage;
    public static final Resource MovingImage;
    public static final Resource Object;
    public static final Resource Multimedia;
    public static final Resource MixedMaterial;
    public static final Resource Print;
    public static final Resource Manuscript;
    public static final Resource Archival;
    public static final Resource Tactile;
    public static final Resource Collection;
    public static final Resource Electronic;
    public static final Resource Note;
    public static final Resource Identifier;
    public static final Resource Unit;
    public static final Resource Role;
    public static final Resource Source;
    public static final Resource Status;
    public static final Resource Agent;
    public static final Resource Person;
    public static final Resource Family;
    public static final Resource Organization;
    public static final Resource Jurisdiction;
    public static final Resource Meeting;
    public static final Resource Topic;
    public static final Resource Temporal;
    public static final Resource Place;
    public static final Resource Event;
    public static final Resource Contribution;
    public static final Resource Content;
    public static final Resource Media;
    public static final Resource Carrier;
    public static final Resource GenreForm;
    public static final Resource Title;
    public static final Resource VariantTitle;
    public static final Resource KeyTitle;
    public static final Resource AbbreviatedTitle;
    public static final Resource ParallelTitle;
    public static final Resource CollectiveTitle;
    public static final Resource Language;
    public static final Resource MusicMedium;
    public static final Resource MusicInstrument;
    public static final Resource MusicEnsemble;
    public static final Resource MusicVoice;
    public static final Resource GeographicCoverage;
    public static final Resource IntendedAudience;
    public static final Resource Arrangement;
    public static final Resource Dissertation;
    public static final Resource Summary;
    public static final Resource Capture;
    public static final Resource Notation;
    public static final Resource ContentAccessibility;
    public static final Resource Script;
    public static final Resource MusicNotation;
    public static final Resource TactileNotation;
    public static final Resource MovementNotation;
    public static final Resource Illustration;
    public static final Resource SupplementaryContent;
    public static final Resource ColorContent;
    public static final Resource SoundContent;
    public static final Resource AspectRatio;
    public static final Resource MusicFormat;
    public static final Resource Scale;
    public static final Resource Cartographic;
    public static final Resource Projection;
    public static final Resource Classification;
    public static final Resource ClassificationDdc;
    public static final Resource ClassificationLcc;
    public static final Resource ClassificationUdc;
    public static final Resource ClassificationNlm;
    public static final Resource Frequency;
    public static final Resource Issuance;
    public static final Resource ProvisionActivity;
    public static final Resource Distribution;
    public static final Resource Manufacture;
    public static final Resource Publication;
    public static final Resource Production;
    public static final Resource AcquisitionSource;
    public static final Resource CopyrightRegistration;
    public static final Resource CoverArt;
    public static final Resource Review;
    public static final Resource TableOfContents;
    public static final Resource Extent;
    public static final Resource BaseMaterial;
    public static final Resource AppliedMaterial;
    public static final Resource Emulsion;
    public static final Resource Mount;
    public static final Resource ProductionMethod;
    public static final Resource Generation;
    public static final Resource Layout;
    public static final Resource BookFormat;
    public static final Resource FontSize;
    public static final Resource Polarity;
    public static final Resource ReductionRatio;
    public static final Resource SoundCharacteristic;
    public static final Resource RecordingMethod;
    public static final Resource RecordingMedium;
    public static final Resource PlayingSpeed;
    public static final Resource GrooveCharacteristic;
    public static final Resource TrackConfig;
    public static final Resource TapeConfig;
    public static final Resource PlaybackChannels;
    public static final Resource PlaybackCharacteristic;
    public static final Resource ProjectionCharacteristic;
    public static final Resource PresentationFormat;
    public static final Resource ProjectionSpeed;
    public static final Resource VideoCharacteristic;
    public static final Resource VideoFormat;
    public static final Resource BroadcastStandard;
    public static final Resource DigitalCharacteristic;
    public static final Resource FileType;
    public static final Resource EncodingFormat;
    public static final Resource FileSize;
    public static final Resource Resolution;
    public static final Resource RegionalEncoding;
    public static final Resource EncodedBitrate;
    public static final Resource CartographicDataType;
    public static final Resource CartographicObjectType;
    public static final Resource ObjectCount;
    public static final Resource SystemRequirement;
    public static final Resource EnumerationAndChronology;
    public static final Resource Enumeration;
    public static final Resource Chronology;
    public static final Resource Sublocation;
    public static final Resource ShelfMark;
    public static final Resource ShelfMarkDdc;
    public static final Resource ShelfMarkLcc;
    public static final Resource ShelfMarkUdc;
    public static final Resource ShelfMarkNlm;
    public static final Resource UsageAndAccessPolicy;
    public static final Resource AccessPolicy;
    public static final Resource UsePolicy;
    public static final Resource RetentionPolicy;
    public static final Resource ImmediateAcquisition;
    public static final Resource Ansi;
    public static final Resource AudioIssueNumber;
    public static final Resource AudioTake;
    public static final Resource Barcode;
    public static final Resource Coden;
    public static final Resource CopyrightNumber;
    public static final Resource DissertationIdentifier;
    public static final Resource Doi;
    public static final Resource Ean;
    public static final Resource Fingerprint;
    public static final Resource Gtin14Number;
    public static final Resource Hdl;
    public static final Resource Isan;
    public static final Resource Isbn;
    public static final Resource Ismn;
    public static final Resource Isni;
    public static final Resource Iso;
    public static final Resource Isrc;
    public static final Resource Issn;
    public static final Resource IssnL;
    public static final Resource Istc;
    public static final Resource Iswc;
    public static final Resource LcOverseasAcq;
    public static final Resource Lccn;
    public static final Resource Local;
    public static final Resource MatrixNumber;
    public static final Resource MusicDistributorNumber;
    public static final Resource MusicPlate;
    public static final Resource MusicPublisherNumber;
    public static final Resource Nbn;
    public static final Resource PostalRegistration;
    public static final Resource PublisherNumber;
    public static final Resource ReportNumber;
    public static final Resource Sici;
    public static final Resource StockNumber;
    public static final Resource Strn;
    public static final Resource StudyNumber;
    public static final Resource Upc;
    public static final Resource Urn;
    public static final Resource VideoRecordingNumber;
    public static final Resource AdminMetadata;
    public static final Resource DescriptionConventions;
    public static final Resource GenerationProcess;
    public static final Resource DescriptionAuthentication;

    // ---- properties ----
    public static final Property identifiedBy;
    public static final Property identifies;
    public static final Property qualifier;
    public static final Property adminMetadata;
    public static final Property date;
    public static final Property place;
    public static final Property agent;
    public static final Property count;
    public static final Property unit;
    public static final Property code;
    public static final Property source;
    public static final Property note;
    public static final Property status;
    public static final Property part;
    public static final Property language;
    public static final Property content;
    public static final Property media;
    public static final Property carrier;
    public static final Property genreForm;
    public static final Property title;
    public static final Property mainTitle;
    public static final Property subtitle;
    public static final Property partNumber;
    public static final Property partName;
    public static final Property variantType;
    public static final Property originDate;
    public static final Property originPlace;
    public static final Property historyOfWork;
    public static final Property musicMedium;
    public static final Property instrument;
    public static final Property instrumentalType;
    public static final Property ensemble;
    public static final Property ensembleType;
    public static final Property voice;
    public static final Property voiceType;
    public static final Property musicSerialNumber;
    public static final Property musicOpusNumber;
    public static final Property musicThematicNumber;
    public static final Property musicKey;
    public static final Property legalDate;
    public static final Property version;
    public static final Property natureOfContent;
    public static final Property geographicCoverage;
    public static final Property temporalCoverage;
    public static final Property intendedAudience;
    public static final Property arrangement;
    public static final Property pattern;
    public static final Property hierarchicalLevel;
    public static final Property organization;
    public static final Property dissertation;
    public static final Property degree;
    public static final Property grantingInstitution;
    public static final Property summary;
    public static final Property capture;
    public static final Property notation;
    public static final Property contentAccessibility;
    public static final Property illustrativeContent;
    public static final Property supplementaryContent;
    public static final Property colorContent;
    public static final Property soundContent;
    public static final Property aspectRatio;
    public static final Property musicFormat;
    public static final Property duration;
    public static final Property scale;
    public static final Property cartographicAttributes;
    public static final Property ascensionAndDeclination;
    public static final Property coordinates;
    public static final Property equinox;
    public static final Property exclusionGRing;
    public static final Property outerGRing;
    public static final Property projection;
    public static final Property awards;
    public static final Property credits;
    public static final Property subject;
    public static final Property classification;
    public static final Property schedulePart;
    public static final Property edition;
    public static final Property itemPortion;
    public static final Property classificationPortion;
    public static final Property spanEnd;
    public static final Property table;
    public static final Property tableSeq;
    public static final Property responsibilityStatement;
    public static final Property editionStatement;
    public static final Property editionEnumeration;
    public static final Property provisionActivityStatement;
    public static final Property seriesStatement;
    public static final Property seriesEnumeration;
    public static final Property subseriesStatement;
    public static final Property subseriesEnumeration;
    public static final Property frequency;
    public static final Property preferredCitation;
    public static final Property issuance;
    public static final Property firstIssue;
    public static final Property lastIssue;
    public static final Property provisionActivity;
    public static final Property copyrightDate;
    public static final Property custodialHistory;
    public static final Property acquisitionTerms;
    public static final Property acquisitionSource;
    public static final Property copyrightRegistration;
    public static final Property coverArt;
    public static final Property review;
    public static final Property tableOfContents;
    public static final Property extent;
    public static final Property dimensions;
    public static final Property baseMaterial;
    public static final Property appliedMaterial;
    public static final Property emulsion;
    public static final Property mount;
    public static final Property productionMethod;
    public static final Property generation;
    public static final Property layout;
    public static final Property bookFormat;
    public static final Property fontSize;
    public static final Property polarity;
    public static final Property reductionRatio;
    public static final Property soundCharacteristic;
    public static final Property projectionCharacteristic;
    public static final Property videoCharacteristic;
    public static final Property digitalCharacteristic;
    public static final Property systemRequirement;
    public static final Property enumerationAndChronology;
    public static final Property heldBy;
    public static final Property sublocation;
    public static final Property physicalLocation;
    public static final Property shelfMark;
    public static final Property electronicLocator;
    public static final Property usageAndAccessPolicy;
    public static final Property immediateAcquisition;
    public static final Property noteType;
    public static final Property relatedTo;
    public static final Property hasInstance;
    public static final Property instanceOf;
    public static final Property hasExpression;
    public static final Property expressionOf;
    public static final Property itemOf;
    public static final Property hasItem;
    public static final Property eventContent;
    public static final Property eventContentOf;
    public static final Property hasEquivalent;
    public static final Property hasPart;
    public static final Property partOf;
    public static final Property accompaniedBy;
    public static final Property accompanies;
    public static final Property hasDerivative;
    public static final Property derivativeOf;
    public static final Property precededBy;
    public static final Property succeededBy;
    public static final Property references;
    public static final Property referencedBy;
    public static final Property issuedWith;
    public static final Property otherPhysicalFormat;
    public static final Property hasReproduction;
    public static final Property reproductionOf;
    public static final Property dataSource;
    public static final Property hasSeries;
    public static final Property seriesOf;
    public static final Property hasSubseries;
    public static final Property subseriesOf;
    public static final Property supplement;
    public static final Property supplementTo;
    public static final Property translation;
    public static final Property translationOf;
    public static final Property originalVersion;
    public static final Property originalVersionOf;
    public static final Property index;
    public static final Property indexOf;
    public static final Property otherEdition;
    public static final Property findingAid;
    public static final Property findingAidOf;
    public static final Property separatedFrom;
    public static final Property splitInto;
    public static final Property replacementOf;
    public static final Property replacedBy;
    public static final Property mergerOf;
    public static final Property mergedToForm;
    public static final Property continues;
    public static final Property continuesInPart;
    public static final Property absorbed;
    public static final Property absorbedBy;
    public static final Property continuedBy;
    public static final Property continuedInPartBy;
    public static final Property contribution;
    public static final Property role;
    public static final Property assigner;
    public static final Property derivedFrom;
    public static final Property changeDate;
    public static final Property creationDate;
    public static final Property descriptionConventions;
    public static final Property descriptionLanguage;
    public static final Property generationProcess;
    public static final Property descriptionModifier;
    public static final Property descriptionAuthentication;
    public static final Property generationDate;

    static {
        Work = m.createResource(NAMESPACE + "Work");
        Instance = m.createResource(NAMESPACE + "Instance");
        Item = m.createResource(NAMESPACE + "Item");
        Text = m.createResource(NAMESPACE + "Text");
        Cartography = m.createResource(NAMESPACE + "Cartography");
        Audio = m.createResource(NAMESPACE + "Audio");
        NotatedMusic = m.createResource(NAMESPACE + "NotatedMusic");
        NotatedMovement = m.createResource(NAMESPACE + "NotatedMovement");
        Dataset = m.createResource(NAMESPACE + "Dataset");
        StillImage = m.createResource(NAMESPACE + "StillImage");
        MovingImage = m.createResource(NAMESPACE + "MovingImage");
        Object = m.createResource(NAMESPACE + "Object");
        Multimedia = m.createResource(NAMESPACE + "Multimedia");
        MixedMaterial = m.createResource(NAMESPACE + "MixedMaterial");
        Print = m.createResource(NAMESPACE + "Print");
        Manuscript = m.createResource(NAMESPACE + "Manuscript");
        Archival = m.createResource(NAMESPACE + "Archival");
        Tactile = m.createResource(NAMESPACE + "Tactile");
        Collection = m.createResource(NAMESPACE + "Collection");
        Electronic = m.createResource(NAMESPACE + "Electronic");
        Note = m.createResource(NAMESPACE + "Note");
        Identifier = m.createResource(NAMESPACE + "Identifier");
        Unit = m.createResource(NAMESPACE + "Unit");
        Role = m.createResource(NAMESPACE + "Role");
        Source = m.createResource(NAMESPACE + "Source");
        Status = m.createResource(NAMESPACE + "Status");
        Agent = m.createResource(NAMESPACE + "Agent");
        Person = m.createResource(NAMESPACE + "Person");
        Family = m.createResource(NAMESPACE + "Family");
        Organization = m.createResource(NAMESPACE + "Organization");
        Jurisdiction = m.createResource(NAMESPACE + "Jurisdiction");
        Meeting = m.createResource(NAMESPACE + "Meeting");
        Topic = m.createResource(NAMESPACE + "Topic");
        Temporal = m.createResource(NAMESPACE + "Temporal");
        Place = m.createResource(NAMESPACE + "Place");
        Event = m.createResource(NAMESPACE + "Event");
        Contribution = m.createResource(NAMESPACE + "Contribution");
        Content = m.createResource(NAMESPACE + "Content");
        Media = m.createResource(NAMESPACE + "Media");
        Carrier = m.createResource(NAMESPACE + "Carrier");
        GenreForm = m.createResource(NAMESPACE + "GenreForm");
        Title = m.createResource(NAMESPACE + "Title");
        VariantTitle = m.createResource(NAMESPACE + "VariantTitle");
        KeyTitle = m.createResource(NAMESPACE + "KeyTitle");
        AbbreviatedTitle = m.createResource(NAMESPACE + "AbbreviatedTitle");
        ParallelTitle = m.createResource(NAMESPACE + "ParallelTitle");
        CollectiveTitle = m.createResource(NAMESPACE + "CollectiveTitle");
        Language = m.createResource(NAMESPACE + "Language");
        MusicMedium = m.createResource(NAMESPACE + "MusicMedium");
        MusicInstrument = m.createResource(NAMESPACE + "MusicInstrument");
        MusicEnsemble = m.createResource(NAMESPACE + "MusicEnsemble");
        MusicVoice = m.createResource(NAMESPACE + "MusicVoice");
        GeographicCoverage = m.createResource(NAMESPACE + "GeographicCoverage");
        IntendedAudience = m.createResource(NAMESPACE + "IntendedAudience");
        Arrangement = m.createResource(NAMESPACE + "Arrangement");
        Dissertation = m.createResource(NAMESPACE + "Dissertation");
        Summary = m.createResource(NAMESPACE + "Summary");
        Capture = m.createResource(NAMESPACE + "Capture");
        Notation = m.createResource(NAMESPACE + "Notation");
        ContentAccessibility = m.createResource(NAMESPACE + "ContentAccessibility");
        Script = m.createResource(NAMESPACE + "Script");
        MusicNotation = m.createResource(NAMESPACE + "MusicNotation");
        TactileNotation = m.createResource(NAMESPACE + "TactileNotation");
        MovementNotation = m.createResource(NAMESPACE + "MovementNotation");
        Illustration = m.createResource(NAMESPACE + "Illustration");
        SupplementaryContent = m.createResource(NAMESPACE + "SupplementaryContent");
        ColorContent = m.createResource(NAMESPACE + "ColorContent");
        SoundContent = m.createResource(NAMESPACE + "SoundContent");
        AspectRatio = m.createResource(NAMESPACE + "AspectRatio");
        MusicFormat = m.createResource(NAMESPACE + "MusicFormat");
        Scale = m.createResource(NAMESPACE + "Scale");
        Cartographic = m.createResource(NAMESPACE + "Cartographic");
        Projection = m.createResource(NAMESPACE + "Projection");
        Classification = m.createResource(NAMESPACE + "Classification");
        ClassificationDdc = m.createResource(NAMESPACE + "ClassificationDdc");
        ClassificationLcc = m.createResource(NAMESPACE + "ClassificationLcc");
        ClassificationUdc = m.createResource(NAMESPACE + "ClassificationUdc");
        ClassificationNlm = m.createResource(NAMESPACE + "ClassificationNlm");
        Frequency = m.createResource(NAMESPACE + "Frequency");
        Issuance = m.createResource(NAMESPACE + "Issuance");
        ProvisionActivity = m.createResource(NAMESPACE + "ProvisionActivity");
        Distribution = m.createResource(NAMESPACE + "Distribution");
        Manufacture = m.createResource(NAMESPACE + "Manufacture");
        Publication = m.createResource(NAMESPACE + "Publication");
        Production = m.createResource(NAMESPACE + "Production");
        AcquisitionSource = m.createResource(NAMESPACE + "AcquisitionSource");
        CopyrightRegistration = m.createResource(NAMESPACE + "CopyrightRegistration");
        CoverArt = m.createResource(NAMESPACE + "CoverArt");
        Review = m.createResource(NAMESPACE + "Review");
        TableOfContents = m.createResource(NAMESPACE + "TableOfContents");
        Extent = m.createResource(NAMESPACE + "Extent");
        BaseMaterial = m.createResource(NAMESPACE + "BaseMaterial");
        AppliedMaterial = m.createResource(NAMESPACE + "AppliedMaterial");
        Emulsion = m.createResource(NAMESPACE + "Emulsion");
        Mount = m.createResource(NAMESPACE + "Mount");
        ProductionMethod = m.createResource(NAMESPACE + "ProductionMethod");
        Generation = m.createResource(NAMESPACE + "Generation");
        Layout = m.createResource(NAMESPACE + "Layout");
        BookFormat = m.createResource(NAMESPACE + "BookFormat");
        FontSize = m.createResource(NAMESPACE + "FontSize");
        Polarity = m.createResource(NAMESPACE + "Polarity");
        ReductionRatio = m.createResource(NAMESPACE + "ReductionRatio");
        SoundCharacteristic = m.createResource(NAMESPACE + "SoundCharacteristic");
        RecordingMethod = m.createResource(NAMESPACE + "RecordingMethod");
        RecordingMedium = m.createResource(NAMESPACE + "RecordingMedium");
        PlayingSpeed = m.createResource(NAMESPACE + "PlayingSpeed");
        GrooveCharacteristic = m.createResource(NAMESPACE + "GrooveCharacteristic");
        TrackConfig = m.createResource(NAMESPACE + "TrackConfig");
        TapeConfig = m.createResource(NAMESPACE + "TapeConfig");
        PlaybackChannels = m.createResource(NAMESPACE + "PlaybackChannels");
        PlaybackCharacteristic = m.createResource(NAMESPACE + "PlaybackCharacteristic");
        ProjectionCharacteristic = m.createResource(NAMESPACE + "ProjectionCharacteristic");
        PresentationFormat = m.createResource(NAMESPACE + "PresentationFormat");
        ProjectionSpeed = m.createResource(NAMESPACE + "ProjectionSpeed");
        VideoCharacteristic = m.createResource(NAMESPACE + "VideoCharacteristic");
        VideoFormat = m.createResource(NAMESPACE + "VideoFormat");
        BroadcastStandard = m.createResource(NAMESPACE + "BroadcastStandard");
        DigitalCharacteristic = m.createResource(NAMESPACE + "DigitalCharacteristic");
        FileType = m.createResource(NAMESPACE + "FileType");
        EncodingFormat = m.createResource(NAMESPACE + "EncodingFormat");
        FileSize = m.createResource(NAMESPACE + "FileSize");
        Resolution = m.createResource(NAMESPACE + "Resolution");
        RegionalEncoding = m.createResource(NAMESPACE + "RegionalEncoding");
        EncodedBitrate = m.createResource(NAMESPACE + "EncodedBitrate");
        CartographicDataType = m.createResource(NAMESPACE + "CartographicDataType");
        CartographicObjectType = m.createResource(NAMESPACE + "CartographicObjectType");
        ObjectCount = m.createResource(NAMESPACE + "ObjectCount");
        SystemRequirement = m.createResource(NAMESPACE + "SystemRequirement");
        EnumerationAndChronology = m.createResource(NAMESPACE + "EnumerationAndChronology");
        Enumeration = m.createResource(NAMESPACE + "Enumeration");
        Chronology = m.createResource(NAMESPACE + "Chronology");
        Sublocation = m.createResource(NAMESPACE + "Sublocation");
        ShelfMark = m.createResource(NAMESPACE + "ShelfMark");
        ShelfMarkDdc = m.createResource(NAMESPACE + "ShelfMarkDdc");
        ShelfMarkLcc = m.createResource(NAMESPACE + "ShelfMarkLcc");
        ShelfMarkUdc = m.createResource(NAMESPACE + "ShelfMarkUdc");
        ShelfMarkNlm = m.createResource(NAMESPACE + "ShelfMarkNlm");
        UsageAndAccessPolicy = m.createResource(NAMESPACE + "UsageAndAccessPolicy");
        AccessPolicy = m.createResource(NAMESPACE + "AccessPolicy");
        UsePolicy = m.createResource(NAMESPACE + "UsePolicy");
        RetentionPolicy = m.createResource(NAMESPACE + "RetentionPolicy");
        ImmediateAcquisition = m.createResource(NAMESPACE + "ImmediateAcquisition");
        Ansi = m.createResource(NAMESPACE + "Ansi");
        AudioIssueNumber = m.createResource(NAMESPACE + "AudioIssueNumber");
        AudioTake = m.createResource(NAMESPACE + "AudioTake");
        Barcode = m.createResource(NAMESPACE + "Barcode");
        Coden = m.createResource(NAMESPACE + "Coden");
        CopyrightNumber = m.createResource(NAMESPACE + "CopyrightNumber");
        DissertationIdentifier = m.createResource(NAMESPACE + "DissertationIdentifier");
        Doi = m.createResource(NAMESPACE + "Doi");
        Ean = m.createResource(NAMESPACE + "Ean");
        Fingerprint = m.createResource(NAMESPACE + "Fingerprint");
        Gtin14Number = m.createResource(NAMESPACE + "Gtin14Number");
        Hdl = m.createResource(NAMESPACE + "Hdl");
        Isan = m.createResource(NAMESPACE + "Isan");
        Isbn = m.createResource(NAMESPACE + "Isbn");
        Ismn = m.createResource(NAMESPACE + "Ismn");
        Isni = m.createResource(NAMESPACE + "Isni");
        Iso = m.createResource(NAMESPACE + "Iso");
        Isrc = m.createResource(NAMESPACE + "Isrc");
        Issn = m.createResource(NAMESPACE + "Issn");
        IssnL = m.createResource(NAMESPACE + "IssnL");
        Istc = m.createResource(NAMESPACE + "Istc");
        Iswc = m.createResource(NAMESPACE + "Iswc");
        LcOverseasAcq = m.createResource(NAMESPACE + "LcOverseasAcq");
        Lccn = m.createResource(NAMESPACE + "Lccn");
        Local = m.createResource(NAMESPACE + "Local");
        MatrixNumber = m.createResource(NAMESPACE + "MatrixNumber");
        MusicDistributorNumber = m.createResource(NAMESPACE + "MusicDistributorNumber");
        MusicPlate = m.createResource(NAMESPACE + "MusicPlate");
        MusicPublisherNumber = m.createResource(NAMESPACE + "MusicPublisherNumber");
        Nbn = m.createResource(NAMESPACE + "Nbn");
        PostalRegistration = m.createResource(NAMESPACE + "PostalRegistration");
        PublisherNumber = m.createResource(NAMESPACE + "PublisherNumber");
        ReportNumber = m.createResource(NAMESPACE + "ReportNumber");
        Sici = m.createResource(NAMESPACE + "Sici");
        StockNumber = m.createResource(NAMESPACE + "StockNumber");
        Strn = m.createResource(NAMESPACE + "Strn");
        StudyNumber = m.createResource(NAMESPACE + "StudyNumber");
        Upc = m.createResource(NAMESPACE + "Upc");
        Urn = m.createResource(NAMESPACE + "Urn");
        VideoRecordingNumber = m.createResource(NAMESPACE + "VideoRecordingNumber");
        AdminMetadata = m.createResource(NAMESPACE + "AdminMetadata");
        DescriptionConventions = m.createResource(NAMESPACE + "DescriptionConventions");
        GenerationProcess = m.createResource(NAMESPACE + "GenerationProcess");
        DescriptionAuthentication = m.createResource(NAMESPACE + "DescriptionAuthentication");

        identifiedBy = m.createProperty(NAMESPACE, "identifiedBy");
        identifies = m.createProperty(NAMESPACE, "identifies");
        qualifier = m.createProperty(NAMESPACE, "qualifier");
        adminMetadata = m.createProperty(NAMESPACE, "adminMetadata");
        date = m.createProperty(NAMESPACE, "date");
        place = m.createProperty(NAMESPACE, "place");
        agent = m.createProperty(NAMESPACE, "agent");
        count = m.createProperty(NAMESPACE, "count");
        unit = m.createProperty(NAMESPACE, "unit");
        code = m.createProperty(NAMESPACE, "code");
        source = m.createProperty(NAMESPACE, "source");
        note = m.createProperty(NAMESPACE, "note");
        status = m.createProperty(NAMESPACE, "status");
        part = m.createProperty(NAMESPACE, "part");
        language = m.createProperty(NAMESPACE, "language");
        content = m.createProperty(NAMESPACE, "content");
        media = m.createProperty(NAMESPACE, "media");
        carrier = m.createProperty(NAMESPACE, "carrier");
        genreForm = m.createProperty(NAMESPACE, "genreForm");
        title = m.createProperty(NAMESPACE, "title");
        mainTitle = m.createProperty(NAMESPACE, "mainTitle");
        subtitle = m.createProperty(NAMESPACE, "subtitle");
        partNumber = m.createProperty(NAMESPACE, "partNumber");
        partName = m.createProperty(NAMESPACE, "partName");
        variantType = m.createProperty(NAMESPACE, "variantType");
        originDate = m.createProperty(NAMESPACE, "originDate");
        originPlace = m.createProperty(NAMESPACE, "originPlace");
        historyOfWork = m.createProperty(NAMESPACE, "historyOfWork");
        musicMedium = m.createProperty(NAMESPACE, "musicMedium");
        instrument = m.createProperty(NAMESPACE, "instrument");
        instrumentalType = m.createProperty(NAMESPACE, "instrumentalType");
        ensemble = m.createProperty(NAMESPACE, "ensemble");
        ensembleType = m.createProperty(NAMESPACE, "ensembleType");
        voice = m.createProperty(NAMESPACE, "voice");
        voiceType = m.createProperty(NAMESPACE, "voiceType");
        musicSerialNumber = m.createProperty(NAMESPACE, "musicSerialNumber");
        musicOpusNumber = m.createProperty(NAMESPACE, "musicOpusNumber");
        musicThematicNumber = m.createProperty(NAMESPACE, "musicThematicNumber");
        musicKey = m.createProperty(NAMESPACE, "musicKey");
        legalDate = m.createProperty(NAMESPACE, "legalDate");
        version = m.createProperty(NAMESPACE, "version");
        natureOfContent = m.createProperty(NAMESPACE, "natureOfContent");
        geographicCoverage = m.createProperty(NAMESPACE, "geographicCoverage");
        temporalCoverage = m.createProperty(NAMESPACE, "temporalCoverage");
        intendedAudience = m.createProperty(NAMESPACE, "intendedAudience");
        arrangement = m.createProperty(NAMESPACE, "arrangement");
        pattern = m.createProperty(NAMESPACE, "pattern");
        hierarchicalLevel = m.createProperty(NAMESPACE, "hierarchicalLevel");
        organization = m.createProperty(NAMESPACE, "organization");
        dissertation = m.createProperty(NAMESPACE, "dissertation");
        degree = m.createProperty(NAMESPACE, "degree");
        grantingInstitution = m.createProperty(NAMESPACE, "grantingInstitution");
        summary = m.createProperty(NAMESPACE, "summary");
        capture = m.createProperty(NAMESPACE, "capture");
        notation = m.createProperty(NAMESPACE, "notation");
        contentAccessibility = m.createProperty(NAMESPACE, "contentAccessibility");
        illustrativeContent = m.createProperty(NAMESPACE, "illustrativeContent");
        supplementaryContent = m.createProperty(NAMESPACE, "supplementaryContent");
        colorContent = m.createProperty(NAMESPACE, "colorContent");
        soundContent = m.createProperty(NAMESPACE, "soundContent");
        aspectRatio = m.createProperty(NAMESPACE, "aspectRatio");
        musicFormat = m.createProperty(NAMESPACE, "musicFormat");
        duration = m.createProperty(NAMESPACE, "duration");
        scale = m.createProperty(NAMESPACE, "scale");
        cartographicAttributes = m.createProperty(NAMESPACE, "cartographicAttributes");
        ascensionAndDeclination = m.createProperty(NAMESPACE, "ascensionAndDeclination");
        coordinates = m.createProperty(NAMESPACE, "coordinates");
        equinox = m.createProperty(NAMESPACE, "equinox");
        exclusionGRing = m.createProperty(NAMESPACE, "exclusionGRing");
        outerGRing = m.createProperty(NAMESPACE, "outerGRing");
        projection = m.createProperty(NAMESPACE, "projection");
        awards = m.createProperty(NAMESPACE, "awards");
        credits = m.createProperty(NAMESPACE, "credits");
        subject = m.createProperty(NAMESPACE, "subject");
        classification = m.createProperty(NAMESPACE, "classification");
        schedulePart = m.createProperty(NAMESPACE, "schedulePart");
        edition = m.createProperty(NAMESPACE, "edition");
        itemPortion = m.createProperty(NAMESPACE, "itemPortion");
        classificationPortion = m.createProperty(NAMESPACE, "classificationPortion");
        spanEnd = m.createProperty(NAMESPACE, "spanEnd");
        table = m.createProperty(NAMESPACE, "table");
        tableSeq = m.createProperty(NAMESPACE, "tableSeq");
        responsibilityStatement = m.createProperty(NAMESPACE, "responsibilityStatement");
        editionStatement = m.createProperty(NAMESPACE, "editionStatement");
        editionEnumeration = m.createProperty(NAMESPACE, "editionEnumeration");
        provisionActivityStatement = m.createProperty(NAMESPACE, "provisionActivityStatement");
        seriesStatement = m.createProperty(NAMESPACE, "seriesStatement");
        seriesEnumeration = m.createProperty(NAMESPACE, "seriesEnumeration");
        subseriesStatement = m.createProperty(NAMESPACE, "subseriesStatement");
        subseriesEnumeration = m.createProperty(NAMESPACE, "subseriesEnumeration");
        frequency = m.createProperty(NAMESPACE, "frequency");
        preferredCitation = m.createProperty(NAMESPACE, "preferredCitation");
        issuance = m.createProperty(NAMESPACE, "issuance");
        firstIssue = m.createProperty(NAMESPACE, "firstIssue");
        lastIssue = m.createProperty(NAMESPACE, "lastIssue");
        provisionActivity = m.createProperty(NAMESPACE, "provisionActivity");
        copyrightDate = m.createProperty(NAMESPACE, "copyrightDate");
        custodialHistory = m.createProperty(NAMESPACE, "custodialHistory");
        acquisitionTerms = m.createProperty(NAMESPACE, "acquisitionTerms");
        acquisitionSource = m.createProperty(NAMESPACE, "acquisitionSource");
        copyrightRegistration = m.createProperty(NAMESPACE, "copyrightRegistration");
        coverArt = m.createProperty(NAMESPACE, "coverArt");
        review = m.createProperty(NAMESPACE, "review");
        tableOfContents = m.createProperty(NAMESPACE, "tableOfContents");
        extent = m.createProperty(NAMESPACE, "extent");
        dimensions = m.createProperty(NAMESPACE, "dimensions");
        baseMaterial = m.createProperty(NAMESPACE, "baseMaterial");
        appliedMaterial = m.createProperty(NAMESPACE, "appliedMaterial");
        emulsion = m.createProperty(NAMESPACE, "emulsion");
        mount = m.createProperty(NAMESPACE, "mount");
        productionMethod = m.createProperty(NAMESPACE, "productionMethod");
        generation = m.createProperty(NAMESPACE, "generation");
        layout = m.createProperty(NAMESPACE, "layout");
        bookFormat = m.createProperty(NAMESPACE, "bookFormat");
        fontSize = m.createProperty(NAMESPACE, "fontSize");
        polarity = m.createProperty(NAMESPACE, "polarity");
        reductionRatio = m.createProperty(NAMESPACE, "reductionRatio");
        soundCharacteristic = m.createProperty(NAMESPACE, "soundCharacteristic");
        projectionCharacteristic = m.createProperty(NAMESPACE, "projectionCharacteristic");
        videoCharacteristic = m.createProperty(NAMESPACE, "videoCharacteristic");
        digitalCharacteristic = m.createProperty(NAMESPACE, "digitalCharacteristic");
        systemRequirement = m.createProperty(NAMESPACE, "systemRequirement");
        enumerationAndChronology = m.createProperty(NAMESPACE, "enumerationAndChronology");
        heldBy = m.createProperty(NAMESPACE, "heldBy");
        sublocation = m.createProperty(NAMESPACE, "sublocation");
        physicalLocation = m.createProperty(NAMESPACE, "physicalLocation");
        shelfMark = m.createProperty(NAMESPACE, "shelfMark");
        electronicLocator = m.createProperty(NAMESPACE, "electronicLocator");
        usageAndAccessPolicy = m.createProperty(NAMESPACE, "usageAndAccessPolicy");
        immediateAcquisition = m.createProperty(NAMESPACE, "immediateAcquisition");
        noteType = m.createProperty(NAMESPACE, "noteType");
        relatedTo = m.createProperty(NAMESPACE, "relatedTo");
        hasInstance = m.createProperty(NAMESPACE, "hasInstance");
        instanceOf = m.createProperty(NAMESPACE, "instanceOf");
        hasExpression = m.createProperty(NAMESPACE, "hasExpression");
        expressionOf = m.createProperty(NAMESPACE, "expressionOf");
        itemOf = m.createProperty(NAMESPACE, "itemOf");
        hasItem = m.createProperty(NAMESPACE, "hasItem");
        eventContent = m.createProperty(NAMESPACE, "eventContent");
        eventContentOf = m.createProperty(NAMESPACE, "eventContentOf");
        hasEquivalent = m.createProperty(NAMESPACE, "hasEquivalent");
        hasPart = m.createProperty(NAMESPACE, "hasPart");
        partOf = m.createProperty(NAMESPACE, "partOf");
        accompaniedBy = m.createProperty(NAMESPACE, "accompaniedBy");
        accompanies = m.createProperty(NAMESPACE, "accompanies");
        hasDerivative = m.createProperty(NAMESPACE, "hasDerivative");
        derivativeOf = m.createProperty(NAMESPACE, "derivativeOf");
        precededBy = m.createProperty(NAMESPACE, "precededBy");
        succeededBy = m.createProperty(NAMESPACE, "succeededBy");
        references = m.createProperty(NAMESPACE, "references");
        referencedBy = m.createProperty(NAMESPACE, "referencedBy");
        issuedWith = m.createProperty(NAMESPACE, "issuedWith");
        otherPhysicalFormat = m.createProperty(NAMESPACE, "otherPhysicalFormat");
        hasReproduction = m.createProperty(NAMESPACE, "hasReproduction");
        reproductionOf = m.createProperty(NAMESPACE, "reproductionOf");
        dataSource = m.createProperty(NAMESPACE, "dataSource");
        hasSeries = m.createProperty(NAMESPACE, "hasSeries");
        seriesOf = m.createProperty(NAMESPACE, "seriesOf");
        hasSubseries = m.createProperty(NAMESPACE, "hasSubseries");
        subseriesOf = m.createProperty(NAMESPACE, "subseriesOf");
        supplement = m.createProperty(NAMESPACE, "supplement");
        supplementTo = m.createProperty(NAMESPACE, "supplementTo");
        translation = m.createProperty(NAMESPACE, "translation");
        translationOf = m.createProperty(NAMESPACE, "translationOf");
        originalVersion = m.createProperty(NAMESPACE, "originalVersion");
        originalVersionOf = m.createProperty(NAMESPACE, "originalVersionOf");
        index = m.createProperty(NAMESPACE, "index");
        indexOf = m.createProperty(NAMESPACE, "indexOf");
        otherEdition = m.createProperty(NAMESPACE, "otherEdition");
        findingAid = m.createProperty(NAMESPACE, "findingAid");
        findingAidOf = m.createProperty(NAMESPACE, "findingAidOf");
        separatedFrom = m.createProperty(NAMESPACE, "separatedFrom");
        splitInto = m.createProperty(NAMESPACE, "splitInto");
        replacementOf = m.createProperty(NAMESPACE, "replacementOf");
        replacedBy = m.createProperty(NAMESPACE, "replacedBy");
        mergerOf = m.createProperty(NAMESPACE, "mergerOf");
        mergedToForm = m.createProperty(NAMESPACE, "mergedToForm");
        continues = m.createProperty(NAMESPACE, "continues");
        continuesInPart = m.createProperty(NAMESPACE, "continuesInPart");
        absorbed = m.createProperty(NAMESPACE, "absorbed");
        absorbedBy = m.createProperty(NAMESPACE, "absorbedBy");
        continuedBy = m.createProperty(NAMESPACE, "continuedBy");
        continuedInPartBy = m.createProperty(NAMESPACE, "continuedInPartBy");
        contribution = m.createProperty(NAMESPACE, "contribution");
        role = m.createProperty(NAMESPACE, "role");
        assigner = m.createProperty(NAMESPACE, "assigner");
        derivedFrom = m.createProperty(NAMESPACE, "derivedFrom");
        changeDate = m.createProperty(NAMESPACE, "changeDate");
        creationDate = m.createProperty(NAMESPACE, "creationDate");
        descriptionConventions = m.createProperty(NAMESPACE, "descriptionConventions");
        descriptionLanguage = m.createProperty(NAMESPACE, "descriptionLanguage");
        generationProcess = m.createProperty(NAMESPACE, "generationProcess");
        descriptionModifier = m.createProperty(NAMESPACE, "descriptionModifier");
        descriptionAuthentication = m.createProperty(NAMESPACE, "descriptionAuthentication");
        generationDate = m.createProperty(NAMESPACE, "generationDate");
    }
}
